### ISSUE TITLE
About nav.relocalizeInMap

### ISSUE THREAD

**Issue by KenImoto** [aldebaran/naoqi_navigation_samples#10]
self.nav.relocalizeInMap([metrical_target.x, metrical_target.y, 0.0])

When I run the above program, it is displayed frequently like below, but could you please tell me why such an error is displayed?

～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～
[INFO ] behavior.box :onInput_onRelocalize:130 Target is too far from explored area.

**Comment by lsouchet** [comment]
The shown error means that the target is out of the explored map. The robot does NOT know how to got to the target. Either you are sending the robot to a target out of the map or there is an issue in the target coordinates computation.

You can retrieve with ALNavigation.getExplorationPath() the points that have been explored and consider that the reach points up to 3m away from the exploration path.

Hope it helps,
Lucas
