### ISSUE TITLE
About nav.navigateToInMap

### ISSUE THREAD

**Issue by KenImoto** [aldebaran/naoqi_navigation_samples#11]
About the program below

 fut = self.nav.navigateToInMap([target[0], target[1], 0.0],     _async=True)

Depending on the value of self.nav.navigateToInMap, 1 may be returned as value even in a place where Pepper can move.
I would like to tell you about its rule.

**Comment by lsouchet** [comment]
@KenImoto Do you still encounter issues about this?

**Comment by KenImoto** [comment]
I had understood this issue.
thank you!!!
