### ISSUE TITLE
Map conversion not working?

### ISSUE THREAD

**Issue by alduxvm** [aldebaran/naoqi_navigation_samples#26]
Hi!

I'm working with the navigation samples and also with my own scripts to do the conversion of the map to image and getting the proper coordinates if we click on a part of the image. I based my code in the ´explorationManager.py´ of this repository, but I'm getting some issues in the coordinates conversion, allow me to explain more. 

Pepper is doing an exploration of a room and then conversion to image (using cv2), the result is here:

![screenshot from 2018-04-27 10-41-00](https://user-images.githubusercontent.com/8823379/39368867-c3fce144-4a08-11e8-8cac-8ae0e3ab5a6c.png)

The relevant code to generate the image is as follows:
```navigation_service.loadExploration(exploration_file)
    map = navigation_service.getMetricalMap()
    map_mpp = map[0]
    map_width = map[1]
    map_height = map[2]
    origin_offset = m.Position2D(map[3])
    map_data = map[4]

    # Occupancy Grid Parameters
    occupancy_map = OccupancyMapParams(map_width, map_mpp, origin_offset)
    occupancy_map.originOffset = origin_offset

    # Conversion from array to CV image
    map_image = np.array(map[4], np.uint8).reshape(map_width, map_height, 1)
    map_image = (100 - map_image) * 2.5 # from 0..100 to 255..0
    map_image = map_image.transpose((1, 0, 2))
    map_image = cv2.resize(map_image, (map_resize, map_resize))
    map_mpp = map_width * map_mpp / map_resize
    map_cv = map_image.astype(np.uint8)
    map_cv_color = cv2.cvtColor(map_cv, cv2.COLOR_GRAY2RGB)
```

When I click in a region on the map, I use the `OccupancyMapParams` class to obtain the position on the map and then send it to the pepper, but the coordinates do not match the location and perhaps the orientation of the map is also wrong... 

Also, I add an image of pepper using the function `navigation_service.getRobotPositionInMap()` and then use the `OccupancyMapParams` class to convert to pixel and print it in the image, but the position is not according to where its on the real map (not even close), sometimes it shows the position of the robot on the grey area of the occupancy map.

**Comment by scarlettfres** [comment]
Hi! I don't know what you do to get the click and display it, but maybe the problem is coming from there. 

Take a look at this script: 
[https://github.com/aldebaran/naoqi_navigation_samples/blob/master/tools/explorationGUI.py
](https://github.com/aldebaran/naoqi_navigation_samples/blob/master/tools/explorationGUI.py)

This script is displaying the map in pygame, then, when you click on it, the robot navigateTo the point.
It could be usefull for you because of these functions at the begining : 

  ```
def getPosition2DFromPixel(self, pixel):
    return m.Position2D(pixel.x * self.mpp + self.originOffset.x, -pixel.y * self.mpp + self.originOffset.y)

  def getPixelFromPosition2D(self, position):
    return m.Position2D((position.x - self.originOffset.x) / self.mpp, (self.originOffset.y - position.y) / self.mpp)
```

Moving from pixel to position and vice versa can be a little bit tricky because it is not the same axis between openCV and ALNavigation.

I hope this will help!

**Comment by alduxvm** [comment]
Thanks a lot, it worked, I messed a couple of lines in my code, thanks for the help!!

**Comment by SajjadRostami** [comment]
Hi @alduxvm, I also have another problem, how I can delete the previous exploration? where is that place? thanks
