### ISSUE TITLE
 About the explorationManager of Places file

### ISSUE THREAD

**Issue by KenImoto** [aldebaran/naoqi_navigation_samples#5]
Which log of the explorationManager in the Places file remains as a log file in the absence of Pepper?
I would like to know the location of the log file.

**Comment by lsouchet** [comment]
Hello,
The behavior on desktop is quite different from the robot which logs into a default log folder.
Without a robot you can specify a system variable to point to the desired log folder.

You can achieve this by doing:
`mkdir /tmp/naoqi_logs`
`QI_SERVICEMANAGER_LOGGING_PATH=/tmp/naoqi_logs/ path/to/naoqi-bin`


Please be aware that running those app on a local NAOqi can only help the purpose of app debugging and tracking regression.
Sensors simulation and hence exploration will not be functional on a local NAOqi.

**Comment by KenImoto** [comment]
Thank you very much.
I'll try logging in the way I taught you
