### ISSUE TITLE
 About getRobotPositionInMap_API

### ISSUE THREAD

**Issue by KenImoto** [aldebaran/naoqi_navigation_samples#6]
Please describe the return value of getRobotPositionInMap_API.
Returned value: [[A, B, C], [D, E, F]]
A is the x coordinate of the current position on the map.
B is the y coordinate of the current position on the map.
I think that,
I would like to ask about other C, D, E, F values.

**Comment by lsouchet** [comment]
Hello,
Please take a look at NAOqi 2.5 documentation.

http://doc.aldebaran.com/2-5/naoqi/motion/exploration-api.html#localized-pose
[A,B,C] basically returns the (x, y, theta) pose of the robot and [D,E,F] is an uncertainty ellipse parametrized by x, y and theta.

**Comment by KenImoto** [comment]
Thank you very much.
I was able to understand about getRobotPositionInMap_API.
