### ISSUE TITLE
How to put motion during navigateToInMapAPI

### ISSUE THREAD

**Issue by KenImoto** [aldebaran/naoqi_navigation_samples#7]
I want to add motion during navigateToInMapAPI.
Is it possible?
Even if you try to add motion while launching navigateToInMap API
It can not operate.
Is Pepper running with navigateToInMapAPI motion-free?

Could you please tell me if there is a way to add motion?

**Comment by lsouchet** [comment]
What kind of motion are you talking about?
During navigateToInMap, the robot can play animations on the arms without problem.
However the head is used for safety purpose to look in the direction of the motion.

Does it help you?

**Comment by KenImoto** [comment]
Thank you for answering my question.

Thanks to you, I understood the problem that motion did not move during navigateToInMapAPI.

It was caused by the motion of the whole body being contained in the motion I created.

I changed the motion to only the arm, I was able to move it.
