### ISSUE TITLE
About navigateToInMapAPI Emergency stop method during startup

### ISSUE THREAD

**Issue by KenImoto** [aldebaran/naoqi_navigation_samples#8]
NavigateToInMapAPI I want to make an emergency stop by touching the Pepper before it hits the object during startup, is there a way?

NavigateToInMapAPI Can I stop emergency during startup?

**Comment by lsouchet** [comment]
Have you really experienced a robot hitting an object during navigateToInMap?
Could you specify what kind of object and the conditions?

Otherwise the common way for interrupting would be to cancel the returned future.
```
#start the navigation
fut = alnavigation.navigateToInMap([1, 0, 0], _async=True)

#do something

#interrupt the navigation
fut.cancel()
```

Let me know if it helps!

**Comment by KenImoto** [comment]
Since there was navigateStopAPI in the sample file, I was wondering if I should use it.
I think I will stop it with fut.cancel.

Thank you!!
