### ISSUE TITLE
 About emergency stop during exploreAPI startup

### ISSUE THREAD

**Issue by KenImoto** [aldebaran/naoqi_navigation_samples#9]
I want to make an emergency stop by touching Pepper before exploreAPI startup, but is there a way?

**Comment by lsouchet** [comment]
There is an API to interrupt the autonomous exploration. 
You can call ALNavigation.stopExploration() for that matter.

Hope it helps!

**Comment by KenImoto** [comment]
I would like to look at using ALNavigation.stopExploration ().
Thank you very much.
